use_frameworks!

platform :ios, '10.0'

target 'ModuleUI_Example' do
  pod 'ModuleUI', :path => '../'

  target 'ModuleUI_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
